#!/usr/bin/env php
<?php
declare(strict_types=1);

/**
 * File: random.php
 *
 * @author      Maciej Sławik <maciekslawik@gmail.com>
 * Github:      https://github.com/maciejslawik
 */

$loopSize = 50000000;

for ($i = 0; $i < $loopSize; $i++) {
    rand();
}

echo 'Randomizer run 50000000 times' . PHP_EOL;
