#!/usr/bin/env php
<?php
declare(strict_types=1);

/**
 * File: sleep.php
 *
 * @author      Maciej Sławik <maciekslawik@gmail.com>
 * Github:      https://github.com/maciejslawik
 */

sleep(3);

echo 'Slept 3 seconds' . PHP_EOL;
